# Documentation
# https://docs.gitlab.com/ee/ci/yaml/

stages:
- test
- deploy

test:
  stage: test
  before_script:
   - git submodule sync --recursive
   - git submodule update --init --recursive
   - nvm i
   - npm i
  script:
   - npm run lint
   - npm run ng -- build fluid-simulation-lib --prod
   - npm run test
   - npm run ng -- build example-app --prod --progress=false

  artifacts:
    paths:
    - dist/fluid-simulation-lib/
    - dist/example-app/
    expire_in: 1337 mins

deploy_master:
  stage: deploy
  script:
     - rsync --delete -rlvvzhe ssh $CI_PROJECT_DIR/dist/example-app/ akehir@192.168.7.111:/app/web/projects/fluid-simulation/master/ # syncronize from build server to local via rsync
     - nvm i
     - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}'>~/.npmrc
     - cd $CI_PROJECT_DIR/dist/fluid-simulation-lib
     - npm publish --access public
   after_script:
     - rm -f ~/.npmrc
  only:
  - master
