
export function getMockWebGlContext() {
  const FRAMEBUFFER_COMPLETE = 0x8CD5;

  const canvas: OffscreenCanvas = {
    convertToBlob: () => Promise.resolve(new Blob()),
    dispatchEvent: () => null,
    oncontextlost: () => null,
    oncontextrestored: () => null,
    transferToImageBitmap: () => ({height: 1, width: 1, close: () => null}),
    addEventListener: () => {},
    getContext: () => null,
    removeEventListener: () => {},
    width: 1,
    height: 1
  };

  return  {
    FRAMEBUFFER_COMPLETE,
    canvas,
    viewport: () => null,
    blendFunc: () => null,
    getExtension: () => ({}),
    enable: () => null,
    disable: () => null,
    getProgramParameter: () => 1,
    clearColor: () => null,
    getSupportedFormat: () => null,
    drawElements: () => null,
    createTexture: () => null,
    bindTexture: () => null,
    texParameteri: () => null,
    texImage2D: () => null,
    createFramebuffer: () => null,
    bindFramebuffer: () => null,
    framebufferTexture2D: () => null,
    checkFramebufferStatus: () => FRAMEBUFFER_COMPLETE,
    createProgram: () => null,
    linkProgram: () => null,
    useProgram: () => null,
    getProgramInfoLog: () => 'getProgramInfoLog',
    createShader: () => null,
    compileShader: () => null,
    attachShader: () => null,
    shaderSource: () => null,
    getShaderParameter: () => 1,
    getShaderInfoLog: () => 'getShaderInfoLog',
    getActiveUniform: () => ({ name: 'activeUniform' }),
    getUniformLocation: () => null,
    getAttribLocation: () => null,
    createBuffer: () => null,
    bindBuffer: () => null,
    bufferData: () => null,
    vertexAttribPointer: () => null,
    enableVertexAttribArray: () => null,
    bindVertexArray: () => null,
    activeTexture: () => null,
    clear: () => null,
    uniform1i: () => null,
    uniform1f: () => null,
    uniform2f: () => null,
    uniform3f: () => null,
    uniform4f: () => null,
  } as unknown as WebGL2RenderingContext;
}
